# Generated by Django 2.2 on 2022-11-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20221119_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='date_and_time',
            field=models.DateTimeField(verbose_name='Дата события'),
        ),
    ]
