# Generated by Django 2.2 on 2022-11-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20221124_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition_employee',
            name='employee_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.Employee', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='exhibition_employee',
            name='exhibition_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.Exhibition', verbose_name='Выставка'),
        ),
        migrations.AlterField(
            model_name='exhibition_museum_piece',
            name='exhibition_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.Exhibition', verbose_name='Выставка'),
        ),
        migrations.AlterField(
            model_name='exhibition_museum_piece',
            name='museum_piece_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.Museum_piece', verbose_name='Экспонат'),
        ),
        migrations.AlterField(
            model_name='exhibition_visitor',
            name='exhibition_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.Exhibition', verbose_name='Выставка'),
        ),
        migrations.AlterField(
            model_name='exhibition_visitor',
            name='visitor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.Visitor', verbose_name='Посетитель'),
        ),
    ]
