# Generated by Django 2.2 on 2022-11-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20221124_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum_piece',
            name='date_of_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
