# Generated by Django 2.2 on 2022-11-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20221124_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum_piece',
            name='author_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='museum_piece',
            name='date_of_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='museum_piece',
            name='hall_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.Hall', verbose_name='Зал'),
        ),
    ]
